WarehouseStock warehouseStock = new WarehouseStock();
WarehouseBookService warehouseBookService = new WarehouseBookService();

// 1
// warehouseBookService.createRecords();
// 2
// System.debug(warehouseBookService.getWarehouseAndRelatedBooks());
// 3
// System.debug(warehouseBookService.getBooks());
// 5
// warehouseStock.calculateBooksPerWarehouse();
// 6
// System.debug(warehouseBookService.getWarehouseAndRelatedBooks());
